CREATE UNIQUE INDEX PRIMARY ON bot (id);
CREATE UNIQUE INDEX user ON cp_user (user_id);
CREATE UNIQUE INDEX index_cp_on_cp_token ON cp (token);
CREATE INDEX index_allow_ip_on_enabled_and_host_ip ON allow_ip (enabled, host_ip);
CREATE INDEX index_cp_on_token_and_label ON cp(token, label);
CREATE INDEX predicate_created ON aiml_predicate (created);
CREATE INDEX index_aiml_predicate_on_user_id_and_bot_id_and_name ON aiml_predicate(user_id, bot_id, name);
CREATE INDEX index_deploy_scheduler_on_completed_and_gubun ON deploy_scheduler(completed, gubun);
CREATE INDEX index_deploy_node_history_on_scheduler_id_and_host_ip ON deploy_node_history(scheduler_id, host_ip);
CREATE INDEX index_bot_on_cp_id_and_sub_label ON bot(cp_id, sub_label);
CREATE INDEX index_bot_file_on_bot_id_and_file_type ON bot_file(bot_id, file_type);
CREATE INDEX index_aiml_images_on_main_id ON aiml_images(main_id);
CREATE INDEX index_aiml_link_on_main_id ON aiml_link(main_id);
CREATE INDEX index_aiml_recommend_on_main_id ON aiml_recommend(main_id);
CREATE INDEX index_aiml_reply_on_main_id ON aiml_reply(main_id);
CREATE INDEX index_aiml_option_on_main_id ON aiml_option(main_id);
CREATE INDEX index_bot_file_on_file_name_and_file_type ON bot_file(file_name, file_type);
CREATE INDEX index_deploy_scheduler_on_sub_label_and_completed_and_gubun ON deploy_scheduler(sub_label,completed,gubun);
CREATE INDEX index_deploy_scheduler_on_cp_id ON deploy_scheduler(cp_id);
CREATE INDEX index_chat_log_on_created_and_cate_name ON chat_log(created, cate_name);